<?php

namespace Database\Seeders;

use App\Models\PricingPlan;
use Illuminate\Database\Seeder;

class PricingPlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'category' => 'real_estate',
                'slug' => 'starter-leads',
                'name' => 'Starter Lead',
                'tier' => 'Starter',
                'value_price' => null,
                'price' => 499,
                'price_note' => '/ Yearly',
                'summary' => 'Starter-friendly. City-focused.',
                'features' => [
                    '20% Referral Fee',
                    '16-20 Referrals / Year',
                    'First TWO (2) Referrals FREE',
                    'Better-qualified referrals',
                    'Select up to 2 Cities or ZIP Codes',
                    'AI Bots + Callers Captured Referrals',
                    '1-Step Verified Prospects',
                    'Basic + Organic Marketing',
                    'Basic Profile Showcase',
                    'Email Support',
                ],
                'cta_label' => 'EXPLORE PLAN',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 0,
            ],
            [
                'category' => 'real_estate',
                'slug' => 'growth-leads',
                'name' => 'Growth Lead',
                'tier' => 'Growth',
                'value_price' => null,
                'price' => 797,
                'price_note' => '/ One-Time',
                'summary' => 'Multi-city. Scalable support.',
                'features' => [
                    'Access to Open Enrollment & 2x Referrals (Q3-Q4, 2026)',
                    '15% Referral Fee',
                    'First FIVE (5) Referrals FREE',
                    '30+ Referrals Till Dec, 2026',
                    'Select up to 5 Cities or ZIP Codes',
                    '3 Hrs / Week of Virtual Assistance',
                    'Email + Text Support',
                    '2-Steps Verified Prospects',
                    'AI + Human Powered Referrals',
                    'Organic + Business Network Marketing',
                    'Virtual pre-screening before showings',
                    'Showcase 5 Listings On Websites',
                    'Premium Profile Showcase',
                    'Quarterly Profile Scorecard',
                    '3 High Revenue Ads / Quarter',
                ],
                'cta_label' => 'EXPLORE PLAN',
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'category' => 'real_estate',
                'slug' => 'elite-leads',
                'name' => 'Elite Lead',
                'tier' => 'Elite',
                'value_price' => null,
                'price' => 2299,
                'price_note' => '/ One-Time',
                'summary' => 'Premium reach. Full-service.',
                'features' => [
                    'Priority Access to Open Enrollment & 2x Referrals (Q3-Q4, 2026)',
                    '10% Referral Fee',
                    'First NINE (9) Referrals FREE',
                    '50+ Referrals Till Dec, 2026',
                    'Select up to 10 Cities or ZIP Codes',
                    '15 Hrs / Week of Virtual Assistance',
                    'Priority Support on Call + Text + Email',
                    '3-Steps Verified Prospects',
                    'AI + Human + Live Connected Referrals',
                    'Full Marketing Toolkit + Templates + Premium SEO',
                    'Showcase 5 Listings on Website',
                    'SEO Optimized Premium Realtor Profile',
                    'Monthly Profile Scorecard',
                    '5 High Revenue Ads / Quarter',
                    'Virtual pre-screening before showings',
                    'Area-specific leads',
                    'Appointment-ready buyers/sellers',
                    'Lead Strategy Planning',
                    'Lead Forecasting & Optimization',
                    'Lead Reporting & Strategy Call - Monthly',
                    'Workflow Tips + Templates to Boost Socials',
                    'Dedicated Accounts Manager',
                ],
                'cta_label' => 'EXPLORE PLAN',
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'category' => 'virtual_assistance',
                'slug' => 'cold-calling-isa',
                'name' => 'Cold Calling / ISA',
                'tier' => 'Dedicated ISA',
                'value_price' => null,
                'price' => 1999,
                'price_note' => '/ Month',
                'summary' => 'Dedicated ISA Sales Agent',
                'features' => [
                    'Data Scraping & Skip Tracing',
                    'Up to 5 Cities / 2 to Callers',
                    'Daily Scheduling + VoIP Config',
                    'CRM Setup + KPI Automation',
                    'Email, Text & Voiceflow Follow-ups',
                    'Weekly Performance Reports',
                    'Key Area Territory Manager',
                    'Social Media Management',
                ],
                'cta_label' => 'EXPLORE PLAN',
                'cta_url' => null,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 0,
            ],
            [
                'category' => 'virtual_assistance',
                'slug' => 'social-media-mgmt',
                'name' => 'Social Media Mgmt',
                'tier' => 'Most Popular',
                'value_price' => null,
                'price' => 1499,
                'price_note' => '/ Month',
                'summary' => 'Daily Long + Short Form Videos',
                'features' => [
                    'IG, FB, LinkedIn + TikTok',
                    'Dedicated Social Media Strategy',
                    'Stories, Highlights + Reels',
                    'Audience Engagement Management',
                    'Custom Ads Creation + Management',
                    'AI Branding & Lead Body Content',
                    'Brand Development + Web SEO',
                    'Monthly + Quarterly Review',
                    'No Cost Calling Support',
                ],
                'cta_label' => 'EXPLORE PLAN',
                'cta_url' => null,
                'is_featured' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'category' => 'virtual_assistance',
                'slug' => 'individual-va',
                'name' => 'Individual VA',
                'tier' => 'Flexible Support',
                'value_price' => null,
                'price' => 8,
                'price_note' => '/ Hour',
                'summary' => 'Flexible Hourly VA Pricing',
                'features' => [
                    'Needs Assessment + Onboarding',
                    '24/7 Discord Priority Support',
                    'Appointment Setting + Calendar',
                    'CRM Support + Email Management',
                    'WordPress / Shopify + SEO & ASO',
                    'Graphic Design + Logo Creation',
                    'Data Entry + Lead Generation',
                    'Automations, Workflows + Templates',
                ],
                'cta_label' => 'EXPLORE PLAN',
                'cta_url' => null,
                'is_featured' => false,
                'is_active' => true,
                'sort_order' => 2,
            ],
        ];

        foreach ($plans as $plan) {
            PricingPlan::updateOrCreate(
                ['slug' => $plan['slug']],
                $plan
            );
        }
    }
}
