<?php

namespace App\Support;

class PricingContent
{
    public static function plans(): array
    {
        return [
            'real_estate' => [
                [
                    'slug' => 'quick-leads',
                    'name' => 'Quick Lead',
                    'tier' => 'Starter Tier',
                    'value_price' => 999,
                    'price' => 499,
                    'price_note' => '/ Yearly · City-Focused Entry',
                    'summary' => 'Entry path built for city-focused agents who want verified contacts and lean marketing.',
                    'features' => [
                        '20% Referral Fee',
                        '16-20 Referrals / Year',
                        'Select up to 2 Cities or Zip Codes',
                        'AI Bots + Callers Captured Referrals',
                        '1-Step Verified Prospects',
                        'Basic + Organic Marketing',
                        'Basic Profile Showcase',
                        'Email Support',
                        'Closing Guarantee Under 150 Days',
                    ],
                    'cta_label' => 'Get Started',
                    'is_featured' => false,
                ],
                [
                    'slug' => 'power-leads',
                    'name' => 'Power Lead',
                    'tier' => 'Growth Tier',
                    'value_price' => 1497,
                    'price' => 797,
                    'price_note' => '/ One-Time · Most Popular Plan',
                    'summary' => 'Balanced qualification depth, faster routing, and virtual assistance support.',
                    'features' => [
                        'Access to Open Enrollment & 2x Referrals (02-03-04, 2026)',
                        '15% Referral Fee',
                        '40+ Quality Referrals Till December 2026',
                        '2-Steps Verified Prospects',
                        'AI + Human Powered Referrals',
                        'Select up to 5 Cities or Zip Codes',
                        '3 Hrs / Week of Virtual Assistance',
                        'Key Accounts Manager for ongoing support and follow-ups',
                        'Email + Text Support',
                        'Organic + Business Network Marketing',
                        'Showcase 3 Listings / Quarter',
                        'Premium Profile Showcase',
                        'Quarterly Profile Scorecard',
                        '3 High Revenue Ads / Quarter',
                        'Closing Guarantee Under 120 Days',
                    ],
                    'cta_label' => 'Get Started',
                    'is_featured' => true,
                ],
                [
                    'slug' => 'prime-leads',
                    'name' => 'Prime Lead',
                    'tier' => 'Elite Tier',
                    'value_price' => 3299,
                    'price' => 2299,
                    'price_note' => '/ One-Time · Full-Service Premium',
                    'summary' => 'Priority routing, connected referrals, and the deepest marketing + support coverage.',
                    'features' => [
                        'Priority Access to Open Enrollment & 2x Referrals (02-03-04, 2026)',
                        '10% Referral Fee',
                        '260+ High Quality Referrals Till December 2026',
                        '3-Steps Verified Prospects',
                        'AI + Human + Live Connected Referrals',
                        'Select up to 10 Cities or Zip Codes',
                        '12 Hrs / Week of Virtual Assistance for extra cold calling & follow-ups',
                        'Priority Support on Call + Text + Email',
                        'Full Marketing Toolkit + Templates + Premium SEO',
                        'Showcase 5 Listings / Quarter',
                        'SEO Optimized Premium Realtor Profile',
                        'Monthly Profile Scorecard',
                        'Closing Guarantee Under 90 Days',
                        '5 High Revenue Ads / Quarter',
                        'Lead Strategy Planning',
                        'Lead Forecasting & Optimization',
                        'Lead Reporting & Strategy Call – Monthly',
                        'Workflow Tips + Templates to Boost Socials',
                        'Dedicated Accounts Manager',
                    ],
                    'cta_label' => 'Get Started',
                    'is_featured' => false,
                ],
            ],
            'virtual_assistance' => [
                [
                    'name' => 'Cold Calling',
                    'tier' => 'ISA Support',
                    'price' => 999,
                    'price_note' => '/ month · Automated Sales',
                    'summary' => 'High-touch ISA outreach with guaranteed seller appointments and live transfers.',
                    'features' => [
                        'Guaranteed Sellers Appointments / Live Transfers + Buyers & Investors',
                        '1x Cold Caller (ISA) – Highly trained + Sales Growth Specialist',
                        'Data Scraping, Skiptracing, Homeowners Data, FSBOs & Vendors',
                        'Strategic profiling of your brand across partner networks',
                        'SEO optimized profiling within industry-specific real estate networks',
                        '2+ Years Experienced ISA’s (Wholesaling, Real Estate, Mortgage)',
                        'Select up to 5 Cities or Zip Codes',
                        'Data (Unlimited) Dialer & VOIP Included',
                        'CRM Support (Text, Email Follow-ups)',
                        'Workflows, Follow-ups, Email & Text Templates + Tips',
                        'Key Accounts Manager',
                    ],
                    'cta_label' => 'Get Overview',
                    'cta_url' => null,
                    'is_featured' => false,
                ],
                [
                    'name' => 'Social Media',
                    'tier' => 'Full Package',
                    'price' => 1499,
                    'price_note' => '/ month · Full Social Package',
                    'summary' => 'Premium social content, engagement, and ads management aligned to campaigns.',
                    'features' => [
                        'High Quality Posts, Reels, Carousels & Videos (5 Posts / Week)',
                        'Guaranteed Organic Leads + Engagement with CTAs',
                        'Client-provided photos, videos or raw content professionally formatted',
                        'Monthly content calendar aligned with promotions & campaigns',
                        'Platform specific planning (Instagram, Facebook, LinkedIn, TikTok)',
                        'Dedicated social media strategy',
                        'Story posting & highlight management',
                        'Audience engagement (likes, comments, interactions)',
                        'Customized Ads Creation & Ads Management',
                        'Branding, Logo Design, Social Media Workflows',
                        'Web Development + Maintenance (WordPress & Shopify)',
                    ],
                    'cta_label' => 'Enroll Now',
                    'cta_url' => null,
                    'is_featured' => true,
                ],
                [
                    'name' => 'Individual VA',
                    'tier' => 'Virtual Assist',
                    'price' => 8,
                    'price_note' => '/ hour · Flexible Engagement',
                    'summary' => 'Flexible hourly support for transactions, outreach, and creative work.',
                    'features' => [
                        'Transaction Coordinator + Social Media Manager',
                        'Outbound & Inbound Calling Specialists',
                        'Receptionist / Front-desk support',
                        'Appointment Scheduling + Chat Support',
                        'CRM Support (Task + Email Follow-ups)',
                        'Web Development + Maintenance (WordPress & Shopify)',
                        'AI Automations, Ads Management & Scaling',
                        'Graphic Design, Logo Design',
                        'Digital Marketing + Lead Generation',
                        'Automations, Workflows, Email & Text Templates',
                    ],
                    'cta_label' => 'Go Prime',
                    'cta_url' => null,
                    'is_featured' => false,
                ],
            ],
        ];
    }
}
